### ISSUE TITLE
Does BCF-IV support non-binary IV?

### ISSUE THREAD

**Issue by minhengw** [fbargaglistoffi/BCF-IV#1]
As title. And my further question is: if the answer is "no", how do researchers usually do to perform BCF-IV or grf's IV Forest with non-binary IV? To do median-split for the IV? or Just abort it? 

Many thanks!
David

**Comment by fbargaglistoffi** [comment]
Hi @minhengw, the package currently doesn't support non-binary IVs. 

However, there are methodologies designed for non-binary IVs. I would suggest you look at the following works by Edward Kennedy (https://academic.oup.com/jrsssb/article/81/1/121/7048355?login=false), and Mike Baiocchi (https://www.tandfonline.com/doi/abs/10.1198/jasa.2010.ap09490, https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4831129/). 

The latter works introduce near-far IV matching (which is implemented in the R package _nearfar_, see https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6207198/) and works for continuous IVs.

Hope this is helpful!

**Comment by minhengw** [comment]
Thank you so much! The papers seem very useful!

David
