### ISSUE TITLE
Error: could not find function "bcf_iv"

### ISSUE THREAD

**Issue by barbarlo** [fbargaglistoffi/BCF-IV#3]
Hi,

I am trying to use your package using Colab (R magic cell).

It seems that I have properly installed the package from github (for example, help(bcf_iv) works) but, when I try to use the function, the following error message pops up:

Error in bcf_iv(y, w, z, x, n_burn = 2000, n_sim = 2000, inference_ratio = 0.5,  : 
  could not find function "bcf_iv"

Could you help me?

Thanks a lot for your time, best regards,

Barbara

**Comment by riccardocadei** [comment]
Hi Barbara,
are you sure the installation concluded successfully and you imported the package via `library("BayesIV")`?

Best regards,
Riccardo

**Comment by barbarlo** [comment]
Hi Ricardo,

Thanks a lot for the quick reply.

Yes, I installed the package (installing first the last version of bcf from
cran archives) and imported the library. The command "help (bcf_iv)" worked
properly.

After reading your message, I thought it could be an issue related to using
Colab so I have used RStudio. But I have the same error: "could not find
function "bcf_iv"". I reproduced it below. I have tested differents ways
(not using the loop "for" or changing the variables) and I have always the
same error.

Thanks again for your time, best regards,

Barbara

> library(devtools)
> install_github("fbargaglistoffi/BCF-IV", ref="master")
Downloading GitHub repo ***@***.***
Skipping 1 packages not available: bcf
── R CMD build
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file
'C:\Users\Baby\AppData\Local\Temp\Rtmp0kxDRE\remotes53447d3e2a6f\fbargaglistoffi-BCF-IV-131ed51/DESCRIPTION'
(348ms)
─  preparing 'BayesIV':
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building 'BayesIV_0.0.1.0.tar.gz'

Installing package into ‘C:/Users/Baby/AppData/Local/R/win-library/4.3’
(as ‘lib’ is unspecified)
* installing *source* package 'BayesIV' ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation
path
* DONE (BayesIV)

> library("BayesIV")

> str(df)
'data.frame': 9011 obs. of  47 variables:
 $ Ref               : chr  "ESP2015-68281-C4-1-R" "ESP2014-54256-C4-1-R"
"ESP2017-87676-C5-5-R" "ESP2015-65712-C5-3-R" ...
 $ Pubindex          : int  0 21 49 7 26 70 16 2 1 28 ...
 $ Q1                : int  0 19 9 7 8 70 16 2 1 25 ...
 $ Pubotras          : int  0 4 0 0 14 2 3 0 0 0 ...
 $ Publib            : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Pubcap            : int  0 0 0 0 9 0 1 0 0 0 ...
 $ Pubopen           : int  0 0 7 0 0 0 0 0 1 10 ...
 $ Pubconex          : int  2 16 0 8 13 18 66 2 2 36 ...
 $ Pubcona           : int  0 5 0 0 9 2 2 0 0 0 ...
 $ Tesisleidas       : int  0 1 1 0 2 0 1 0 0 1 ...
 $ Tesison           : int  0 3 1 1 2 1 2 0 0 2 ...
 $ Pat               : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Patlic            : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Patexp            : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Colab             : int  0 0 0 0 1 0 0 0 0 0 ...
 $ Contradm          : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Contradm_num      : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Contradm_fin      : num  0 0 0 0 0 0 0 0 0 0 ...
 $ Contraempna       : int  0 1 0 0 0 1 1 0 0 0 ...
 $ Contraempna_num   : int  0 5 0 0 0 2 8 0 0 0 ...
 $ Contraempna_fin   : num  0 1409273 0 0 0 ...
 $ Contraempex       : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Contraempex_num   : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Contraempex_fin   : num  0 0 0 0 0 0 0 0 0 0 ...
 $ Ebt               : int  0 0 0 0 0 0 0 0 0 0 ...
 $ H2020             : int  0 0 0 0 0 0 0 0 0 0 ...
 $ H2020_num         : int  0 0 0 0 0 0 0 0 0 0 ...
 $ H2020_fin         : num  NA NA NA NA NA NA NA NA NA NA ...
 $ Conv              : Factor w/ 3 levels "JIN","PGC","RTI": 3 3 3 3 3 3 3
3 3 3 ...
 $ Area              : Factor w/ 21 levels "AGL","AYA","BFU",..: 12 12 12
12 12 12 12 12 12 12 ...
 $ Sol               : num  18248615 12387859 10872851 8857447 8692544 ...
 $ Con               : num  79860 2057000 1899700 1718200 471900 ...
 $ DifSolCon         : num  18168755 10330859 8973151 7139247 8220644 ...
 $ Planea            : int  0 0 1 1 0 1 0 0 0 0 ...
 $ Accede_original   : chr  "0" "0" "2" "2" ...
 $ Accede_0_0        : int  0 0 1 1 0 1 0 0 0 0 ...
 $ Accede_14_0       : int  0 0 1 1 0 1 0 0 0 0 ...
 $ Accede_145_0      : int  0 0 1 1 0 1 0 0 0 0 ...
 $ Acceso_precon     : int  0 0 0 0 0 0 0 0 0 0 ...
 $ ICTS_original     : chr  "0" "0" "35" "35" ...
 $ Nota              : num  3.5 4 4.64 4.4 3.82 4.03 3.76 4.05 3.7 3.75 ...
 $ Tipo_sol          : Factor w/ 9 levels "CID","EMPPY",..: 8 8 7 7 9 7 8 7
7 8 ...
 $ ICTS              : Factor w/ 30 levels "0","1","2","3",..: 1 1 23 23 1
23 1 1 1 1 ...
 $ ICTSarea          : Factor w/ 10 levels "0","1","2","3",..: 1 1 9 9 1 9
1 1 1 1 ...
 $ GrupoICTS_original: num  2 2 1 1 0 1 2 0 0 2 ...
 $ ICTS_Grupo23      : num  30 30 NA NA NA NA 30 NA NA 30 ...
 $ GrupoICTS         : int  1 1 1 1 0 1 1 0 0 1 ...

> resultados_sig_pos <- c("Pubindex","Q1","Pubopen")

> for (i in resultados_sig_pos) {
+   Y = df [,i]
+   D = df [,"Accede_14_0"]
+   Z = df [,"GrupoICTS"]
+   X =  df [,"Area"]
+   bcf_iv(Y, D, Z, X,
+        n_burn = 2000,
+        n_sim = 2000,
+        inference_ratio = 0.5,
+        binary = FALSE,
+        max_depth = 2,
+        adj_method = "holm")
+ cat("\n")
+ print(paste("Heterogeneidad por AREA de la VARIABLE RESULTADO:", i))
+ print(bcf_iv)
+ cat("\n")
+ }
Error in bcf_iv(Y, D, Z, X, n_burn = 2000, n_sim = 2000, inference_ratio =
0.5,  :
  could not find function "bcf_iv"




<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by riccardocadei** [comment]
Hi Barbara,
Thank you very much for pointing out this issue: `bcf_iv` was not correctly exported.
I have just fixed it in the last [commit](https://github.com/fbargaglistoffi/BCF-IV/commit/e4036d9430320acfbcadb391ac8d33744aad33a5). Try to re-install the package now.

Best regards,
Riccardo

**Comment by barbarlo** [comment]
Thank you!

The function works now, but I got other error: Error in sample.int(length(x),
size, replace, prob) :

  invalid 'size' argument


I found a similar issue in Stackoverflow, but I couldn´t manage to fix it:
https://stackoverflow.com/questions/28204484/error-in-sample-intlengthx-size-replace-prob-invalid-first-argument

I don´t know if the problem is in my data or in the function. I tell you
just in case it´s the last one.

Thanks a lot, best regards,

Barbara


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by riccardocadei** [comment]
This new error seems related to your data-generating process, but I cannot guess without further documentation. Could you document it in more detail in a new issue? 

I am closing here this issue we solved.
