### ISSUE TITLE
Function bartc cannot be found

### ISSUE THREAD

**Issue by jschobin** [fbargaglistoffi/BCF-IV#5]
I was testing your package for a heterogeneity analysis of an intervention we performed. I get an error that states that the function bartc cannot be found. This is probably a dependency issue. From which package stems bartc???

**Comment by fbargaglistoffi** [comment]
Hi @jschobin, you are getting this error because you haven't installed the package _bartCause_ that contains the _bartc_ function (see https://rdrr.io/cran/bartCause/man/bartc.html).

Closing this issue. And opening a new one here: https://github.com/fbargaglistoffi/BCF-IV/issues/6
